[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://your-backend-api.com/api/v1"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://your-backend-api.com/api/v1"

[context.branch-deploy.environment]
  NEXT_PUBLIC_API_URL = "https://your-backend-api.com/api/v1"

[[plugins]]
  package = "@netlify/plugin-nextjs"