[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "frontend/.next"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "cd frontend && npm run dev"
  port = 8888
  targetPort = 3002
  framework = "#custom"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
