runtime: go121

env_variables:
  PORT: 8080
  ENVIRONMENT: production
  # Add your environment variables here
  # DATABASE_URL: "your-database-url"
  # JWT_SECRET: "your-jwt-secret"

automatic_scaling:
  min_instances: 0
  max_instances: 10