services:
  - type: web
    name: heal-backend
    env: go
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        generateValue: true
      - key: JWT_SECRET
        generateValue: true